"""empty message

Revision ID: 50867f0cfe3b
Revises: e55f96ae1293
Create Date: 2025-04-03 21:15:37.541617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50867f0cfe3b'
down_revision = 'e55f96ae1293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('creators', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('melody_battle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['melody_battle_id'], ['melody_battle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    # ### end Alembic commands ###
